### ISSUE TITLE
Windows XP Chino Tradicional (CP950) problema

### ISSUE THREAD

**Issue by AndyChiu** [UniversoLibreMexicoAC/descargar-cfdi#3]
Hola Mauricio Baeza:

reporta dos errors:

uno, db.py  import util tinen error "ImportError: cannot import name 'util' " :
----------------------------------------------------------------------------------------------------------------------------------
D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi>descarga-cfdi.py -h
Traceback (most recent call last):
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descarga-cfdi.py", line 24, i
n <module>
    from descargacfdi import util
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descargacfdi\util.py", line 2
4, in <module>
    from . import db
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descargacfdi\db.py", line 8,
in <module>
    from . import util
ImportError: cannot import name 'util'
----------------------------------------------------------------------------------------------------------------------------------

yo modifica add # en db.py line 8 para no ejecuta y luego no sale ImportError, pero ya no funcional para guardar XML a SQLite

y otro error (segunto) es no hay sale mesage help en otro lng code sistema :
----------------------------------------------------------------------------------------------------------------------------------
D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi>descarga-cfdi.py --help
Traceback (most recent call last):
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descarga-cfdi.py", line 319,
in <module>
    main()
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descarga-cfdi.py", line 312,
in main
    ok, opt, filters = make_filters()
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descarga-cfdi.py", line 232,
in make_filters
    args = process_command_line_arguments()
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descarga-cfdi.py", line 225,
in process_command_line_arguments
    args=parser.parse_args()
  File "C:\Python34\lib\argparse.py", line 1728, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Python34\lib\argparse.py", line 1760, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Python34\lib\argparse.py", line 1966, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Python34\lib\argparse.py", line 1906, in consume_optional
    take_action(action, args, option_string)
  File "C:\Python34\lib\argparse.py", line 1834, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Python34\lib\argparse.py", line 1016, in __call__
    parser.print_help()
  File "C:\Python34\lib\argparse.py", line 2359, in print_help
    self._print_message(self.format_help(), file)
  File "C:\Python34\lib\argparse.py", line 2365, in _print_message
    file.write(message)
UnicodeEncodeError: 'cp950' codec can't encode character '\xd1' in position 485:
 illegal multibyte sequence
----------------------------------------------------------------------------------------------------------------------------------

pienso este error es mi sistema lng code es cp950, y no puede sale unicode, si yo elimiar letra especial(acento y ñ) y guadar , se pueden sale mesage --help

pero si usa opcion, se pueden trabajo bien, y -rfc -ciec y -log es funcional muy bien!
pero si usa --help o opcion  vacio, luego sale mensage --help y tienen error.

mi sistema : Windows XP Chino Tradicional (CP950)

Gracias!

**Comment by mauriciobaeza** [comment]
O sea que tu lengua materna es el chino?

Definitivamente NO debes de quitar ningún **import**...

Prueba con esta rama donde he eliminado acentos y ñ para ver si se corrigen los errores que mencionas: 
https://github.com/UniversoLibreMexicoAC/descargar-cfdi/tree/emitidas

Saludos

**Comment by AndyChiu** [comment]
si! chino tradicional, ya prueba y ya sale informacion de Help
pero primero error todavia existe:
-----------------------------------------------------------------------------------------------------------------------
D:\My Documents\Downloads\descargar-cfdi-emitidas>descarga-cfdi.py
Traceback (most recent call last):
  File "D:\My Documents\Downloads\descargar-cfdi-emitidas\descarga-cfdi.py", lin
e 22, in <module>
    from uuid import UUID
  File "D:\My Documents\Downloads\descargar-cfdi-emitidas\descargacfdi\util.py",
 line 24, in <module>
    from . import db
  File "D:\My Documents\Downloads\descargar-cfdi-emitidas\descargacfdi\db.py", l
ine 8, in <module>
    from . import util
ImportError: cannot import name 'util'
-----------------------------------------------------------------------------------------------------------------------

**Comment by mauriciobaeza** [comment]
Lo unico que se me ocurre es que sea tu estorno, confirmame que estas usando Win XP, Python 3.4 para probar en la misma configuracion.

Saludos

**Comment by mauriciobaeza** [comment]
Vuelve a descargar la rama **emitidas** y pruebas...

**Comment by AndyChiu** [comment]
Bueno Dias Mauricio:
hoy yo para pruebas, ya no hay sale error de 'util', pero cuanto guardar xml a sqlite, hay sale error:
___________________________________________________________________________
....
04/05/2016 08:16:08 -CFDI-DEBUG-download_xml-151 - Descargando documento 4 de 4
04/05/2016 08:16:10 -CFDI-INFO-save_download-77 - Guardando documentos...
Traceback (most recent call last):
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descarga-cfdi.py", line 317,
in <module>

  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descarga-cfdi.py", line 312,
in main
    ok, opt, filters = make_filters()
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descargacfdi\util.py", line 5
2, in descarga_cfdi
    limit, parcial = consulta_descarga(sat, f, opt['target'])
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descargacfdi\util.py", line 1
09, in consulta_descarga
    db.save_download(invoices)
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descargacfdi\db.py", line 85,
 in save_download
    values['xml'] = load_file(invoice[2])
  File "D:\CONTABILIDAD_ELECTRONICA\descargar-cfdi\descargacfdi\db.py", line 70,
 in load_file
    data = f.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0xbf in position 2: illegal
multibyte sequence

D:\My Documents\Downloads\descargar-cfdi-emitidas (1)\descargar-cfdi-emitidas>
___________________________________________________________________________

**Comment by mauriciobaeza** [comment]
Pues no las guardes en la base de datos, jejejeje... en serio, primero prueba NO guardarlos en la base de datos, solo descargalos y verifica que puedes verlos sin problemas...

Si todo esta bien, al guardarlos... se podría intentar guardar con tu encoding (cp950), pero... aquí viene algo importante, el estándar del SAT para los XML es UTF-8

Si aun asi quieres probar, intenta cambiar esta linea:
https://github.com/UniversoLibreMexicoAC/descargar-cfdi/blob/emitidas/descargacfdi/db.py#L70

por...

    data = f.read().decode('cp950')

nunca he trabajo con idioma chino, así que no sabria decirte más...

Saludos

**Comment by AndyChiu** [comment]
jajajaja.. si, yo ahorita solo guardar xml y no importar a sqlite, pero no hay pasa nada,  solo reporta  mi situación.
yo ahorita usa Access VBA para cambiar trabarjo, guardar xml y importa informacion a Access 
Gracias su ayudar! :)

**Comment by mauriciobaeza** [comment]
prueba lo que te comento, a ver si funciona... por ahora damos por resuelto el problema por el que abriste este tema.

Saludos
