### ISSUE TITLE
ImportError: No module named 'requests.packages'

### ISSUE THREAD

**Issue by pixelead0** [UniversoLibreMexicoAC/descargar-cfdi#4]
Al ejecutar:

```
python3 descarga-cfdi -h
```

Me sale el siguiente error:
```
Traceback (most recent call last):
  File "descarga-cfdi", line 24, in <module>
    from descargacfdi import util
  File "/home/pixelead0/Escritorio/descargar-cfdi/descargacfdi/util.py", line 15, in <module>
    from requests.packages.urllib3 import disable_warnings
ImportError: No module named 'requests.packages'
```

He validado que tenga instalado requests y urllib3
```
sudo pip3 show requests urllib3 
```

```
---
Name: requests
Version: 2.2.1
Location: /usr/lib/python3/dist-packages
Requires: 
---
Name: urllib3
Version: 1.7.1
Location: /usr/lib/python3/dist-packages
Requires: 

```

Utilizo Linux Mint 17.2
python 3.4.3

**Comment by pixelead0** [comment]
Actualicé a las versiones actuales de requests y urllib3, pero el error continua.

Comenté las lineas 15 y 44: 

```
15  #from requests.packages.urllib3 import disable_warnings
.
.
.
44  #disable_warnings()
```
